
#include "wx/wxprec.h"
#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif
#include "wx/evtloop.h"
#include "wx/treectrl.h"

class MyApp: public wxApp
{
public:
	virtual bool OnInit();
	virtual void ExitMainLoop();
	wxFrame *CreateFrame();
};

class BasicFrame: public wxFrame
{
public:
	BasicFrame(wxFrame *frame, const wxString& title, const wxPoint& pos, const wxSize& size, const long style);
	virtual ~BasicFrame();
	void CreateControls();
	DECLARE_EVENT_TABLE()
};

enum
{
	ID_PANEL,
	ID_TREECTRL,
};

//DECLARE_APP(MyApp)
//IMPLEMENT_APP_NO_MAIN(MyApp)
IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
	if ( !wxApp::OnInit() )
		return false;
	SetExitOnFrameDelete(true);
	CreateFrame();
	return true;
}

void MyApp::ExitMainLoop()
{
	// instead of existing wxWidgets main loop, terminate the MFC one
	::PostQuitMessage(0);
}

wxFrame *MyApp::CreateFrame()
{
	BasicFrame *subframe = new BasicFrame(NULL, wxT("Canvas Frame"), wxPoint(10, 10), wxSize(300, 300),
		wxDEFAULT_FRAME_STYLE);
	subframe->SetTitle(wxT("wxWidgets treectrl  frame"));
	subframe->Show(true);
	return subframe;
}

BEGIN_EVENT_TABLE(BasicFrame, wxFrame)
END_EVENT_TABLE()

BasicFrame::BasicFrame(wxFrame *frame, const wxString& title, const wxPoint& pos, const wxSize& size, const long style)
: wxFrame(frame, -1, title, pos, size, style)
{
	CreateControls();
}

BasicFrame::~BasicFrame()
{
	if ( IsLastBeforeExit() )
		PostQuitMessage(0);
}

void BasicFrame::CreateControls()
{    
	////@begin BasicFrame content construction
	// Generated by DialogBlocks, 28/02/2013 01:45:07 (unregistered)

	BasicFrame* itemFrame1 = this;

	wxPanel* itemPanel2 = new wxPanel( itemFrame1, ID_PANEL, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL );

	wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxVERTICAL);
	itemPanel2->SetSizer(itemBoxSizer3);

	wxTreeCtrl* itemTreeCtrl4 = new wxTreeCtrl( itemPanel2, ID_TREECTRL, wxDefaultPosition, wxSize(200, 400), wxTR_HAS_BUTTONS |wxTR_LINES_AT_ROOT|wxTR_ROW_LINES|wxTR_SINGLE );
	itemBoxSizer3->Add(itemTreeCtrl4, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

	wxTreeItemId rootId = itemTreeCtrl4->AddRoot(wxT("Root"));
	itemTreeCtrl4->AppendItem( rootId, "test1" );
	itemTreeCtrl4->AppendItem( rootId, "test2" );
	itemTreeCtrl4->AppendItem( rootId, "test3" );
	itemTreeCtrl4->AppendItem( rootId, "test4" );
	wxTreeItemId parentId = itemTreeCtrl4->AppendItem( rootId, "test5" );
	itemTreeCtrl4->AppendItem( parentId, "test6" );
	itemTreeCtrl4->Expand(rootId);
	itemTreeCtrl4->Expand(parentId);


	wxToolBar *toolBar = CreateToolBar();
	wxBitmap toolBarBitmaps[1];
	toolBarBitmaps[0] = wxBITMAP(copy);
	toolBar->AddTool(wxID_NEW, wxT("New"), toolBarBitmaps[0]);

	////@end BasicFrame content construction
	//itemTreeCtrl4->Refresh();
// 	wxSize size = GetClientSize();
// 	itemTreeCtrl4->SetSize(0,0,size.x,size.y);
// 	itemTreeCtrl4->Refresh();
// 	Refresh();
}
